name: CI Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  strategy:
    matrix:
      php_version:
        - 8.3
        - 8.4
  build:
    runs-on: ubuntu-latest

    env:
      COMPOSE_FILE: compose.yaml
      PHP_VERSION=${{ matrix.php_version }}

    steps:
    - uses: actions/checkout@v4

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        target: ci
        push: false
        load: true
        tags: recruiterphp/byte-units-php:php-${{ matrix.php_version }}-latest
        build-args: |
          PHP_VERSION=${{ matrix.php_version }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Run test suite
      run: make test
